version: "3"

services:
  app:
    build: .
    volumes:
      - ./:/usr/src/test
    depends_on:
      - mysql

  mysql:
    hostname: mysql
    image: mysql:8.0.22 # fails
    # image: mysql:8.0.21 # works
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    expose:
      - 3306
    ports:
      - 3306:3306
